---
title: "MC2 Data Landscape Survey"
author: "Sage Bionetworks"
date: "1/4/2023"
output:
  html_document:
    css: style.css
    includes:
      in_header: header.html
      in_footer: footer.html
  pdf_document: default
params:
  portalName: Cancer Complexity Knowledge Portal
  portalURL: https://www.cancercomplexity.synapse.org/
  dsp_core_config: dsp_core_config.yml
  data: "../../../../../tests/test.json" # required if rendering to PDF
---

```{r echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(formd))
load(file = "formd-mc2.RData")
.F <- formInputContext(params$dsp_core_config, params$data)
```

## Project information

**Project Title** `r RIA(.F$projectTitle)`

**Project Description** `r RIA(.F$projectDescription)`

**Project Grant Number** `r RIA(.F$projectGrantId)`

**Name of Principal Investigator** `r RIA(.F$projectPI)`

**Email Address of Principal Investigator** `r RIA(.F$projectPIEmail)`

**Name of Point of Contact (Data Coordinator)** `r RIA(.F$projectPOC)`

**Email Address of Point of Contact** `r RIA(.F$projectPOCEmail)`

**Name of Institution** `r RIA(.F$projectInstitution)`

**Project End Date** `r RIA(.F$projectEndDate)`


## Resource information

By providing information on the datasets, computational tools, and models you plan to share over the next year, you will help us determine how we prioritize and support:

- metadata standards adoption
- data transfer to [NIH-supported repositories](https://www.nlm.nih.gov/NIHbmic/domain_specific_repositories.html)
- expansion of the [`r params$portalName`](`r params$portalURL`)

### Directions for survey

**Type your answers into the table cells below. Controlled fields will display terms we have on file when you begin typing. You are not required to select a term from this list if a suitable entry is not currently available. For each assay, tool, or model, please add a separate row to the corresponding table.**

### Datasets
#### Fields:
- **Assay**: Controlled field; the assay used to generate the dataset that will be shared

- **Format**: Controlled field; the format used to store the shared data

- **Sample count**: The number of samples for which data will be shared. For single cell experiments, each cell should be counted as a single sample.

- **Species**: Controlled field; the species of origin for the dataset being shared. _Human-derived data may require specific resource sharing considerations._

- **Data repository**: Name of the storage service where data will be housed.

- **Planned upload date**: The date by which you plan to upload data to the identified repository.

<!-- Deposit table starts here -->
#### Dataset information {#deposits}

`r RIA(.F$datasetTable)`

### Tools and computational models
#### Fields:
- **Function**: Controlled field; the primary functionality of the computational tool or model.

- **Type**: Controlled field; how the tool or model has been implemented for access by other users.

- **Topic**: Controlled field; general scientific domain the software or model serves.

#### Computational tool or model information {#tools}

`r RIA(.F$toolTable)`

`r RIA(.F$dspCoreVersion)`
