---
title: "Introductory info"
author: "Sage Bionetworks"
date: "2/14/2023"
output: html_document
params:
  helpDocsLink: NA
  dccEmail: mc2center@sagebase.org
  mainEmail: orion.banks@sagebase.org
  DCC: MC2 Center
  portalName: Cancer Complexity Knowledge Portal
  portalURL: https://www.cancercomplexity.synapse.org/
  synURL: https://www.synapse.org/
  fundingAgency: NCI
  embargoPeriod: the embargo period
  community: MC2
---

## Before you begin 

The Multi-Consortia Coordinating (MC^2^) Center at Sage Bionetworks is intended to promote data, tool, and expertise exchange among members of associated National Cancer Institute Division of Cancer Biology consortia, including:

- Cancer Systems Biology Consortium
- Physical Sciences in Oncology Network
- Cancer Tissue Engineering Collaborative
- Cellular Cancer Biology Imaging Research initiative
- Metastasis Research Network
- Patient-Derived Models of Cancer

To help Sage Bionetworks support resource sharing within the MC^2^ Center, we are requesting that all members provide a few details about the projects they are working on for their respective grants. __Contributing information via this form is voluntary and does not require your eventual distribution of resources.__

Tentative resource curation process:

1. Resources are generated and ultimately transferred to NIH-supported repositories (independently by generators or guided by the MC^2^ Center) or otherwise appropriate destinations compliant with the [NIH Data Management and Sharing Policy](https://sharing.nih.gov/data-management-and-sharing-policy)
2. Metadata describing the resource(s) are provided by generators and captured by Sage Bionetworks according to standardized models agreed upon by the community
3. Sage Bionetworks stores metadata using the secure [Synapse platform](`r params$synURL`)
4. Resources are listed on the [`r params$portalName`](`r params$portalURL`)

**Please note**: Sage Bionetworks does not require datasets, tools, or resources for the MC^2^ Center to be stored via Synapse. Our goal is to help ensure data is FAIR (Findable, Accessible, Interoperable, and Reusable) and housed in NIH-supported repositories. A list of supported repositories can be found [here](https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/repositories-for-sharing-scientific-data) and NIH guidelines for selecting a repository can be found [here](https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/selecting-a-data-repository). 

For general questions about this survey, please contact `r params$mainEmail`. 

To begin, please provide the information requested below for the grant you are working on. If you are working on multiple grants, please submit a form for each one.