---
title: "MC2 Data Landscape Survey"
author: "Sage Bionetworks"
date: "3/31/2023"
output:
  html_document:
    css: style.css
    includes:
      in_header: ../configs/header.html
      in_footer: ../configs/footer.html
  pdf_document: default
params:
  portalName: Cancer Complexity Knowledge Portal
  portalURL: https://www.cancercomplexity.synapse.org/
  dsp_core_config: ../configs/dsp_core_config.yml
  data: "../../../../../tests/test.json" # required if rendering to PDF
---

```{r echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(formd))
load(file = "../tools/formd-mc2.RData") #load modified functions
.F <- formInputContext(params$dsp_core_config, params$data)
```

# Project information
**_Fields marked with <span style="color:red">\*</span> are required_**  

**Name of Principal Investigator(s) <span style="color:red">\*</span> **  
Please enter multiple PI names as a comma-separated list.  
`r RIA(.F$projectPI)`

**Email Address of Principal Investigator(s) <span style="color:red">\*</span> **  
Please enter multiple PI emails as a comma-separated list.  
`r RIA(.F$projectPIEmail)`  

**Grant Number**  
Optional, but recommended. If you are unsure which number corresponds to your current grant, [NIH RePORTER](https://reporter.nih.gov/advanced-search) can be used to identify your grant ID.  
`r RIA(.F$projectGrantId)`  

**Name of Point of Contact (Resource Coordinator) <span style="color:red">\*</span> **  
Please provide the name of the individual you want us to contact with questions about resource sharing by your group.  
`r RIA(.F$projectPOC)`  

**Email Address of Point of Contact <span style="color:red">\*</span> **  
Please provide the email address of the individual listed as Point of Contact above.  
`r RIA(.F$projectPOCEmail)`  

# Resource information

By providing information on the datasets, computational tools, and models you plan to share over the next year, you will help us determine how we prioritize and support:

- metadata standards design and implementation
- data transfer to [NIH-supported repositories](https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/repositories-for-sharing-scientific-data)
- expansion of the [`r params$portalName`](`r params$portalURL`)

### Directions for survey

**Type your answers into the table cells below. Controlled fields will display terms we have on file when you begin typing. You are not required to select a term from this list if a suitable entry is not currently available. For each assay, tool, or model, please add a separate row to the corresponding table.**
